
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Library_IS2
{

using System;
    using System.Collections.Generic;
    
public partial class Book
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Book()
    {

        this.BookReview = new HashSet<BookReview>();

    }


    public long Id_Book { get; set; }

    public string Book_Name { get; set; }

    public string ISBN { get; set; }

    public short Year { get; set; }

    public Nullable<long> ID_Author { get; set; }



    public virtual Author Author { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BookReview> BookReview { get; set; }

    public virtual UserBook UserBook { get; set; }

}

}
